# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: blue-svc
  annotations:
    harness.io/primary-service: "true"
spec:
  type: LoadBalancer
  selector:
    app: app1  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
