/*
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
      version: blue
  template:
    metadata:
      labels:
        app: app1
        version: blue
    spec:
      containers:
      - name: app1
        image: harshini1402/harness-deployment-repo:version-1
        ports:
        - containerPort: 80
*/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: app1
    harness.io/color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
      harness.io/color: blue
  template:
    metadata:
      labels:
        app: app1
        harness.io/color: blue
    spec:
      containers:
      - name: app1
        image: harshini1402/harness-deployment-repo:version-1
        ports:
        - containerPort: 80

