apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness
      version: blue
  template:
    metadata:
      labels:
        app: harness
        version: blue
    spec:
      containers:
        - name: harness-v1.0-cont
          image: harshini1402/harness-deployment-repo:v1.0
          ports:
            - containerPort: 7000
