---
apiVersion: v1
kind: Service
metadata:
  name: blue-svc
  annotations:
    harness.io/primary-service: "true"
spec:
  selector:
    app: app1
    version: blue  # Harness will swap this to green during promotion
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
    

# apiVersion: v1
# kind: Service
# metadata:
#   name: blue-svc
#   annotations:
#     harness.io/primary-service: "true"
# spec:
#   type: LoadBalancer
#   selector:
#     app: app1
#     harness.io/color: green
#     version: blue
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80

