apiVersion: v1
kind: Service
metadata: 
  name: harness-blue-service
  annotations:
    harness.io/primary-service: "true"
spec: 
  selector: 
    app: harness
    version: blue
  ports:
      - protocol: TCP
        port: 80
        targetPort: 7000
  type: LoadBalancer
