# app1-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
      version: blue
  template:
    metadata:
      labels:
        app: app1
        version: blue  # added version label for clarity
    spec:
      containers:
      - name: app1
        image: harshini1402/harness-deployment-repo:version-1
        ports:
        - containerPort: 80
