# Dockerfile.app1
FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y nginx telnet && \
    mkdir -p /var/www/html/app1 && \
    chmod -R 755 /var/www/html

# Only for /app2 route, not root
COPY v2-index.html /var/www/html/app2/index.html

# COPY v2-index.html /var/www/html/index.html

EXPOSE 80 

CMD ["nginx", "-g", "daemon off;"]
