# Dockerfile.app1
FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y nginx telnet && \
    mkdir -p /var/www/html/app1 && \
    chmod -R 755 /var/www/html

COPY v1-index.html /var/www/html/app1/index.html
COPY v1-index.html /var/www/html/index.html # This serves root / with v1

EXPOSE 80  #Expose port 80 for Nginx

CMD ["nginx", "-g", "daemon off;"]
