---
apiVersion: v1
kind: Service
metadata:
  name: green-svc
  annotations:
    harness.io/stage-service: "true"
spec:
  selector:
    app: app1
    version: green  # Harness will swap this to blue during promotion
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

# apiVersion: v1
# kind: Service
# metadata:
#   name: green-svc
#   annotations:
#     harness.io/stage-service: "true"
# spec:
#   type: LoadBalancer
#   selector:
#     app: app1
#     harness.io/color: blue
#     version: green
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80
