
# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: green-svc
  annotations:
    harness.io/stage-service: "true"
spec:
  type: LoadBalancer
  selector:
    app: app2  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
