apiVersion: v1
kind: Service
metadata:
  name: harness-green-service
  annotations:
    harness.io/stage-service: "true"
spec:
  selector:
    app: harness
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: LoadBalancer
