apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  annotations: 
    harness.io/direct-apply: "true"
  labels:
    harness.io/color: green #green during next deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness
      version: green
  template:
    metadata:
      labels:
        app: harness
        version: green
    spec:
      containers:
        - name: harness-v2-cont
          image: harshini1402/harness-deployment-repo:2.0
          ports:
            - containerPort: 7000
