# app2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  annotations: 
    harness.io/direct-apply: "true"
  labels:
    harness.io/color: green 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: harshini1402/harness-deployment-repo:version-2
        ports:
        - containerPort: 80
