apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    harness.io/color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
      version: green
  template:
    metadata:
      labels:
        app: app1
        version: green
    spec:
      containers:
      - name: app2
        image: harshini1402/harness-deployment-repo:version-2
        ports:
        - containerPort: 80
