# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: version1-svc
spec:
  type: LoadBalancer
  selector:
    app: app1  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
