# Apex - Primary service
apiVersion: v1
kind: Service
metadata:
  name: my-app-primary-service  # Apex service name
  annotations:
    harness.io/primary-service: "true"
spec:
  selector:
    app: my-app
    version: primary
  ports:
    - port: 80            # External port
      targetPort: 8080    # Container port
  type: LoadBalancer
  
---
# Canary Service

apiVersion: v1
kind: Service
metadata:
  name: my-app-canary-service
spec:
  selector:
    app: my-app
    version: canary
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
