apiVersion: split.smi-spec.io/v1alpha3
kind: TrafficSplit
metadata:
  name: my-app-traffic-split
  namespace: default
spec:
  service: my-app-service  # Apex service that clients access
  backends:
    - service: my-app-service         # Points to primary version
      weight: 80
    - service: my-app-canary-service  # Points to canary version
      weight: 20
